name: Build a PDF from Coursework MD files
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  watch:
    types: [ started ]
    # file paths to consider in the event. Optional; defaults to all.
    paths:
      - '.coursework/*'

jobs:
  build:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mrtj/actions-makepdfs@master
        if: github.ref == 'refs/heads/master'
        with:
          markdown_dir: .coursework
          output_dir: .coursework
          assets_dir: .coursework/assets
      - uses: actions/upload-artifact@v1
        with:
          name: veoir-coursework
          path: .coursework