name: Build a PDF from Coursework MD files
# This workflow is triggered on pushes to the repository.
on:
  pull_request:
    branches:
      - master
    # file paths to consider in the event. Optional; defaults to all.
    paths:
      - '.coursework/*'

jobs:
  build:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mrtj/actions-makepdfs@master
      - uses: actions/upload-artifact@v1
        with:
          name: veoir-coursework
          markdown_dir: '.coursework'
          output_dir: '.coursework'