name: Coursework PDF
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  watch:
    types: [ started ]

jobs:
  build:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: baileyjm02/markdown-to-pdf@master
        if: github.ref == 'refs/heads/master'
        with:
          input_dir: .coursework
          output_dir: .coursework
          images_dir: .coursework/images
          image_import: ./images
      - uses: actions/upload-artifact@v1
        with:
          name: veoir-coursework
          path: .coursework
